news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: 'h2 a'
      article_body: 'div .field-name-body'
      article_title: '.Encabezado-Articulo h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: 'h2[class ~= "c_t"] a'
      article_body: 'div[class = "a_c clearfix"] p'
      article_title: 'header div h1'
  elreforma:
    url: https://www.reforma.com/
    queries:
      homepage_article_links: 'h1 a, h2 a, h3 a'
      article_body: 'div p[class ~= "textoMovil"]'
      article_title: 'div h1'
